// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:trans_flutter/models/ai_model.dart';
import 'package:trans_flutter/models/provider_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AIModelAdapter());
    registerAdapter(ProviderModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AIModelAdapter());
    registerAdapter(ProviderModelAdapter());
  }
}
